# Generated by Django 5.2 on 2025-05-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.CharField(max_length=2000)),
                ('tipo_plato', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SUSHI', 'Sushi'), ('PLATO_PRINCIPAL', 'Plato_principal'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida')], default='ENTRANTE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nombreUsuario', models.CharField(max_length=100, verbose_name='nombre')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COCINERO', 'Cocinero'), ('CAMARERO', 'Camarero'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='umamihouse_user_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='umamihouse_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('mail', models.EmailField(max_length=150)),
                ('imagen_url', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=500)),
                ('fecha_nacimiento', models.DateField()),
                ('mail', models.EmailField(max_length=150)),
                ('imagen_url', models.CharField(max_length=1000)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COCINERO', 'Cocinero'), ('CAMARERO', 'Camarero'), ('CLIENTE', 'Cliente')], default='COCINERO', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Pedido_linea', models.ManyToManyField(to='umamihouseapp.pedidolinea')),
            ],
        ),
        migrations.AddField(
            model_name='pedidolinea',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='umamihouseapp.plato'),
        ),
    ]
