# Generated by Django 5.2.1 on 2025-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0002_remove_empleado_user_remove_mesa_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidolinea',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidolinea',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
