# Generated by Django 5.2 on 2025-05-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0002_user_apellido_user_nombre_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidolinea',
            name='plato',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoLinea',
        ),
    ]
