# Generated by Django 5.2 on 2025-05-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0003_alter_pedidolinea_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidolinea',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(null=True, verbose_name='fecha_reserva')),
                ('hora_reserva', models.TimeField(null=True, verbose_name='hora_reserva')),
                ('numero_personas', models.IntegerField(default=1, max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
