# Generated by Django 5.2 on 2025-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0004_alter_pedidolinea_cantidad_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.IntegerField(default=1),
        ),
    ]
