# Generated by Django 5.2 on 2025-05-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0004_pedido_pedidolinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombreUsuario',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COCINERO', 'Cocinero'), ('CAMARERO', 'Camarero'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10),
        ),
    ]
