# Generated by Django 5.2.1 on 2025-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0005_remove_user_nombreusuario_user_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='fecha_nacimiento'),
        ),
    ]
