# Generated by Django 5.2 on 2025-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0006_alter_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Preparando'), (2, 'En proceso'), (3, 'Finalizado')], default=1),
        ),
    ]
