# Generated by Django 5.2.1 on 2025-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0006_alter_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoMesa', models.CharField(choices=[('RESERVADA', 'Reservada'), ('OCUPADA', 'Ocupada'), ('DISPONIBLE', 'Disponible')], default='DISPONIBLE', max_length=50)),
            ],
        ),
    ]
