# Generated by Django 5.2 on 2025-05-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0007_mesa'),
        ('umamihouseapp', '0007_pedido_estado'),
    ]

    operations = [
    ]
