# Generated by Django 5.2.1 on 2025-05-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0007_mesa'),
        ('umamihouseapp', '0007_pedido_estado'),
    ]

    operations = [
    ]
