# Generated by Django 5.2.1 on 2025-05-20 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamihouseapp', '0009_cliente_fecha_creacion_cliente_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mesa',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
